services:
  sharpj-discovery-service:
    build: ./descovery-service
    container_name: sharpj-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
  sharpj-config-service:
    build: ./config-service
    container_name: sharpj-config-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - DISCOVERY_SERVICE_URL=http://sharpj-discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
    depends_on:
      sharpj-discovery-service:
        condition: service_healthy
  sharpj-gateway-service:
    build: ./gateway-service
    container_name: sharpj-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      sharpj-discovery-service:
        condition: service_healthy
      sharpj-config-service:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://sharpj-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sharpj-config-service:8080/
